create table public.kategori (
    id         bigint generated by default as identity primary key,
    kode       text not null unique,
    nama       text not null,
    deskripsi  text,
    is_active  boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.supplier (
    id         bigint generated by default as identity primary key,
    name       text not null,
    contact    text,
    phone      text,
    address    text,
    is_active  boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.customer (
    id         bigint generated by default as identity primary key,
    name       text not null,
    phone      text,
    address    text,
    price_tier text not null default 'p1' check (price_tier in ('p1','p2','p3','p4')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.barang (
    id           bigint generated by default as identity primary key,
    kode         text not null unique,
    nama         text not null,
    category_id  bigint references public.kategori(id) on delete set null,
    mitra        text,
    tipe         text,
    stok         integer not null default 0,
    modal        integer not null default 0,
    p1           integer not null default 0,
    p2           integer not null default 0,
    p3           integer not null default 0,
    p4           integer not null default 0,
    lokasi_item  text,
    lokasi_stock text,
    notes        text,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

create index barang_category_id_idx on public.barang (category_id);

-- Keep updated_at honest without having to remember to set it
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

create trigger kategori_set_updated_at before update on public.kategori
  for each row execute function public.set_updated_at();
create trigger supplier_set_updated_at before update on public.supplier
  for each row execute function public.set_updated_at();
create trigger customer_set_updated_at before update on public.customer
  for each row execute function public.set_updated_at();
create trigger barang_set_updated_at   before update on public.barang
  for each row execute function public.set_updated_at();