import React, { useState, useEffect } from 'react';

/**
 * CategoryFormModal
 * Shared modal for creating and editing kategori records.
 * Kode is auto-generated by the backend on create, and is read-only on edit.
 */
export default function CategoryFormModal({ isOpen, mode, initialData, onSave, onCancel }) {
  const [formState, setFormState] = useState({ nama: '', deskripsi: '', isActive: true });
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (isOpen) {
      setError(null);
      setFormState({
        nama: initialData?.nama || '',
        deskripsi: initialData?.deskripsi || '',
        isActive: initialData ? String(initialData.isActive).toUpperCase() === 'TRUE' : true
      });
    }
  }, [isOpen, initialData]);

  if (!isOpen) return null;

  const handleChange = (field, value) => {
    setFormState(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async () => {
    if (!formState.nama.trim()) {
      setError('Nama kategori wajib diisi');
      return;
    }

    try {
      setIsSaving(true);
      setError(null);

      const payload = {
        nama: formState.nama.trim(),
        deskripsi: formState.deskripsi.trim(),
        isActive: formState.isActive ? 'TRUE' : 'FALSE'
      };

      const isEditMode = mode === 'edit';
      const url = isEditMode ? '/api/kategori/update' : '/api/kategori/create';
      if (isEditMode) payload.id = initialData.id;

      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      const result = await res.json();

      if (res.ok) {
        onSave();
      } else {
        setError(result.message || 'Gagal menyimpan kategori');
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 backdrop-blur-sm px-4">
      <div className="bg-[#141923] border border-[#1f293d] rounded-lg p-6 w-full max-w-md shadow-2xl">
        <h2 className="text-lg font-bold text-slate-100 mb-4">
          {mode === 'edit' ? 'Edit Kategori' : 'Tambah Kategori'}
        </h2>

        {initialData?.kode && (
          <div className="mb-4">
            <label className="block text-xs font-semibold text-slate-400 mb-1 uppercase tracking-wide">Kode</label>
            <input
              type="text"
              value={initialData.kode}
              disabled
              className="w-full bg-[#0f131c] border border-[#2b384e] rounded px-3 py-2 text-slate-500 text-sm cursor-not-allowed"
            />
          </div>
        )}

        <div className="mb-4">
          <label className="block text-xs font-semibold text-slate-400 mb-1 uppercase tracking-wide">Nama Kategori</label>
          <input
            type="text"
            value={formState.nama}
            onChange={(e) => handleChange('nama', e.target.value)}
            placeholder="Contoh: Lampu"
            className="w-full bg-[#0f131c] border border-[#2b384e] rounded px-3 py-2 text-slate-100 text-sm focus:outline-none focus:border-blue-500"
          />
        </div>

        <div className="mb-4">
          <label className="block text-xs font-semibold text-slate-400 mb-1 uppercase tracking-wide">Deskripsi</label>
          <textarea
            value={formState.deskripsi}
            onChange={(e) => handleChange('deskripsi', e.target.value)}
            placeholder="Contoh: Semua"
            rows="2"
            className="w-full bg-[#0f131c] border border-[#2b384e] rounded px-3 py-2 text-slate-100 text-sm focus:outline-none focus:border-blue-500 resize-none"
          />
        </div>

        <div className="mb-6 flex items-center justify-between bg-[#0f131c] border border-[#2b384e] rounded px-3 py-2.5">
          <span className="text-sm text-slate-300">Status Aktif</span>
          <button
            type="button"
            onClick={() => handleChange('isActive', !formState.isActive)}
            className={`relative w-10 h-5 rounded-full transition-colors ${formState.isActive ? 'bg-emerald-500' : 'bg-slate-600'}`}
          >
            <span className={`absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full transition-transform ${formState.isActive ? 'translate-x-5' : 'translate-x-0'}`} />
          </button>
        </div>

        {error && <p className="text-rose-400 text-xs mb-4">{error}</p>}

        <div className="flex gap-3 justify-end">
          <button
            onClick={onCancel}
            disabled={isSaving}
            className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-slate-300 font-semibold rounded transition-all disabled:opacity-50"
          >
            Batal
          </button>
          <button
            onClick={handleSubmit}
            disabled={isSaving}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded transition-all disabled:opacity-50"
          >
            {isSaving ? 'Menyimpan...' : mode === 'edit' ? 'Simpan' : 'Tambah Kategori'}
          </button>
        </div>
      </div>
    </div>
  );
}